"""
test_phase2_cleaning.py
-----------------------
Unit and integration test suite for Phase 2 Data Cleaning & Transformation.
Validates:
  1. JDS blank row elimination (171 -> 139), target validity, skill boundaries [1, 5], sensitivity dataset (137).
  2. SDS column sanitation, 161 row preservation, trait boundaries [17, 68], target validity.
  3. Data Science Jobs salary parsing, strict monotonicity (min <= avg <= max), spreads, log hiring volume.
  4. Analytics Jobs experience interval parsing, discrete salary bracket transformation,
     top-50 skill indicators, 7 location clusters, 6 role families, text imputation.
  5. Cryptographic raw dataset immutability (SHA-256 byte-for-byte invariance).
"""

import os
import unittest
import pandas as pd
from src.preprocessing.load_raw import verify_raw_integrity, compute_file_hash


class TestPhase2DataCleaning(unittest.TestCase):
    """Test suite ensuring all Phase 2 transformations satisfy specifications."""

    @classmethod
    def setUpClass(cls):
        """Load processed and interim datasets generated by Phase 2 pipeline."""
        cls.raw_jds_path = "data/raw/JDS Skill Traits.xlsx"
        cls.raw_sds_path = "data/raw/SDS Personality Traits.xlsx"
        cls.raw_ds_path = "data/raw/DataScience Jobs.csv"
        cls.raw_aj_path = "data/raw/Analytics Jobs.csv"

        cls.interim_jds = pd.read_csv("data/interim/jds_interim.csv")
        cls.interim_sds = pd.read_csv("data/interim/sds_interim.csv")
        cls.interim_ds = pd.read_csv("data/interim/data_science_jobs_interim.csv")
        cls.interim_aj = pd.read_csv("data/interim/analytics_jobs_interim.csv")

        cls.jds_baseline = pd.read_csv("data/processed/jds_processed.csv")
        cls.jds_sensitivity = pd.read_csv("data/processed/jds_sensitivity_3291_removed.csv")
        cls.sds_processed = pd.read_csv("data/processed/sds_processed.csv")
        cls.ds_processed = pd.read_csv("data/processed/data_science_jobs_processed.csv")
        cls.aj_processed = pd.read_csv("data/processed/analytics_jobs_processed.csv")

    # -------------------------------------------------------------------------
    # 1. JDS Cleaning Tests
    # -------------------------------------------------------------------------
    def test_jds_row_counts_and_blank_removal(self):
        """Verify exactly 32 blank trailing rows were removed, yielding N=139 baseline and N=137 sensitivity."""
        self.assertEqual(len(self.interim_jds), 139)
        self.assertEqual(len(self.jds_baseline), 139)
        self.assertEqual(len(self.jds_sensitivity), 137)
        self.assertNotIn(3291, self.jds_sensitivity["id"].values)

    def test_jds_column_names_and_types(self):
        """Verify column header standardization and zero null values."""
        self.assertIn("maths_stats_skills", self.jds_baseline.columns)
        self.assertNotIn("maths-stats_skills", self.jds_baseline.columns)
        self.assertEqual(self.jds_baseline.isna().sum().sum(), 0)

    def test_jds_skill_ranges_and_target(self):
        """Verify skill scores reside in [1.0, 5.0] and target is binary {0, 1}."""
        skill_cols = [
            "big_data_skills", "maths_stats_skills", "coding_skills",
            "ai_and_ml_skills", "dashboard_and_storytelling_skills"
        ]
        for col in skill_cols:
            self.assertTrue((self.jds_baseline[col] >= 1.0).all())
            self.assertTrue((self.jds_baseline[col] <= 5.0).all())
        self.assertEqual(set(self.jds_baseline["salary_hike_high_or_low"].unique()), {0, 1})
        self.assertEqual((self.jds_baseline["salary_hike_high_or_low"] == 1).sum(), 73)
        self.assertEqual((self.jds_baseline["salary_hike_high_or_low"] == 0).sum(), 66)

    # -------------------------------------------------------------------------
    # 2. SDS Cleaning Tests
    # -------------------------------------------------------------------------
    def test_sds_row_count_and_sanitized_headers(self):
        """Verify all 161 rows preserved, headers sanitized to snake_case."""
        self.assertEqual(len(self.sds_processed), 161)
        expected_cols = [
            "id", "neuroticism", "extraversion", "openness_to_experience",
            "agreeableness", "conscientiousness", "success_classification_high_low"
        ]
        self.assertListEqual(list(self.sds_processed.columns), expected_cols)
        self.assertEqual(self.sds_processed.isna().sum().sum(), 0)

    def test_sds_trait_ranges_and_target(self):
        """Verify psychometric scores are in empirical range [17, 68] and target is {0, 1}."""
        trait_cols = [
            "neuroticism", "extraversion", "openness_to_experience",
            "agreeableness", "conscientiousness"
        ]
        for col in trait_cols:
            self.assertTrue((self.sds_processed[col] >= 17.0).all())
            self.assertTrue((self.sds_processed[col] <= 68.0).all())
        self.assertEqual(set(self.sds_processed["success_classification_high_low"].unique()), {0, 1})
        self.assertEqual((self.sds_processed["success_classification_high_low"] == 1).sum(), 85)
        self.assertEqual((self.sds_processed["success_classification_high_low"] == 0).sum(), 76)

    def test_sds_duplicate_ids_preserved(self):
        """Verify exactly 9 duplicate IDs (18 rows) are retained."""
        dup_ids = self.sds_processed[self.sds_processed["id"].duplicated(keep=False)]["id"].unique()
        self.assertEqual(len(dup_ids), 9)

    # -------------------------------------------------------------------------
    # 3. Data Science Jobs Cleaning Tests
    # -------------------------------------------------------------------------
    def test_data_science_jobs_row_count_and_salary_parsing(self):
        """Verify all 1,602 rows retained, salary parsed without nulls, and strict ordering min <= avg <= max."""
        self.assertEqual(len(self.ds_processed), 1602)
        salary_cols = ["min_salary_lakh", "avg_salary_lakh", "max_salary_lakh"]
        for col in salary_cols:
            self.assertIn(col, self.ds_processed.columns)
            self.assertEqual(self.ds_processed[col].isna().sum(), 0)
            self.assertTrue((self.ds_processed[col] > 0).all())

        # Strict ordering verification
        ordering_valid = (
            (self.ds_processed["min_salary_lakh"] <= self.ds_processed["avg_salary_lakh"]) &
            (self.ds_processed["avg_salary_lakh"] <= self.ds_processed["max_salary_lakh"])
        ).all()
        self.assertTrue(ordering_valid)

    def test_data_science_jobs_spread_and_log_volume(self):
        """Verify spread and log10 hiring volume derivation."""
        self.assertTrue((self.ds_processed["salary_spread_lakh"] >= 0).all())
        self.assertTrue((self.ds_processed["salary_spread_ratio"] >= 0).all())
        self.assertTrue((self.ds_processed["log10_num_of_jobs"] >= 0).all())

    # -------------------------------------------------------------------------
    # 4. Analytics Jobs Cleaning Tests
    # -------------------------------------------------------------------------
    def test_analytics_jobs_row_count_and_experience_intervals(self):
        """Verify 15,841 rows retained and experience intervals satisfy min <= max."""
        self.assertEqual(len(self.aj_processed), 15841)
        self.assertEqual(self.aj_processed["min_experience"].isna().sum(), 0)
        self.assertEqual(self.aj_processed["max_experience"].isna().sum(), 0)
        self.assertTrue((self.aj_processed["min_experience"] <= self.aj_processed["max_experience"]).all())
        self.assertTrue((self.aj_processed["midpoint_experience"] >= self.aj_processed["min_experience"]).all())

    def test_analytics_jobs_salary_bracket_mapping(self):
        """Verify salary_rank in 1..6, midpoint in 1.5..37.5, and is_high_salary in {0, 1}."""
        self.assertEqual(set(self.aj_processed["salary_rank"].unique()), {1, 2, 3, 4, 5, 6})
        self.assertTrue((self.aj_processed["salary_midpoint"] >= 1.5).all())
        self.assertTrue((self.aj_processed["salary_midpoint"] <= 37.5).all())
        self.assertEqual(set(self.aj_processed["is_high_salary"].unique()), {0, 1})

    def test_analytics_jobs_top_k_skills(self):
        """Verify exactly 50 binary indicator columns created with zero missing values."""
        skill_cols = [c for c in self.aj_processed.columns if c.startswith("skill_")]
        self.assertEqual(len(skill_cols), 50)
        for col in skill_cols:
            self.assertTrue(set(self.aj_processed[col].unique()).issubset({0, 1}))

    def test_analytics_jobs_macro_locations_and_roles(self):
        """Verify exactly 7 location clusters and 6 role families."""
        expected_clusters = {
            "Bengaluru", "NCR", "Mumbai", "Pune", "Hyderabad", "Chennai", "Other/Tier-2"
        }
        self.assertEqual(set(self.aj_processed["location_cluster"].unique()), expected_clusters)

        expected_roles = {
            "Data Scientist", "Data Analyst", "Business Analyst",
            "Data Engineer", "BI Developer", "Non-Analytics/Other"
        }
        self.assertEqual(set(self.aj_processed["job_role_family"].unique()), expected_roles)

    def test_analytics_jobs_text_cleaning(self):
        """Verify text cleaning: job_type_clean has no nulls, key_skills_clean has no nulls, and job_description imputed empty strings."""
        self.assertEqual(self.aj_processed["job_type_clean"].isna().sum(), 0)
        self.assertEqual(self.aj_processed["key_skills_clean"].isna().sum(), 0)
        # Empty strings are written as empty fields in CSV and parse as NaN on standard CSV load.
        # Verify that length metadata is 100% non-null and exactly 3,508 imputed entries have length 0.
        self.assertEqual(self.aj_processed["job_description_char_count"].isna().sum(), 0)
        self.assertEqual(self.aj_processed["job_description_word_count"].isna().sum(), 0)
        self.assertEqual((self.aj_processed["job_description_char_count"] == 0).sum(), 3508)

    # -------------------------------------------------------------------------
    # 5. Cryptographic Raw Immutability Test
    # -------------------------------------------------------------------------
    def test_raw_dataset_cryptographic_immutability(self):
        """Verify all raw datasets match their baseline SHA-256 digests byte-for-byte."""
        df_integrity = verify_raw_integrity()
        self.assertTrue(df_integrity["is_identical"].all())
        self.assertEqual((df_integrity["status"] == "PASS").sum(), 4)


if __name__ == "__main__":
    unittest.main()
